# Generated by Django 3.1.5 on 2021-02-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210214_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/products', verbose_name='Product_Image'),
        ),
    ]
