# Generated by Django 3.1.5 on 2021-01-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210130_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'created'), ('R', 'reviwed')], default='C', max_length=10),
        ),
    ]
